version: '3.8'
services:
  logger:
    build: .
    volumes:
      - ./logger.py:/app/logger.py
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"





#version: '3.1'

#services:
 # app:
  #  build: .
    #depends_on:
     # - mongo
    #environment:
     # - MONGO_URI=mongodb://mongo:27017/
    #restart: always

  #mongo:
   # image: mongo
    #ports:
     # - "27017:27017"
