apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
      - name: etl
        image: europe-west1-docker.pkg.dev/bubbly-pillar-410707/ourbestrepo/etl
        env:
          - name: MONGO_URI
            value: "mongodb://mongo:27017/"
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "weather"
        imagePullPolicy: IfNotPresent
